### ISSUE TITLE
Configure using yaml

### ISSUE THREAD

**Issue by slarwise** [slarwise/nvim-config#2]
It would be nice. Then we get this for free:

- Validation. Create a json schema for e.g. all options and allowed values. Can validate config without starting neovim.
- completion with a schema
- easier to merge in others config
- simpler/stupider/easier to read than lua

```yaml
options:
  shiftwidth: 4
  background: dark
mappings:
  normal:
    <c-j>: <cmd>cnext<cr>
    sf: <cmd>Telescope find_files<cr>
autocmds:
  TermEnter: startinsert
languages:
  golang:
    options:
      softtabstop: 4
    lsp:
      command: gopls
  markdown:
    syntax:
      link:
        markdownerror: none
lsp:
  mappings:
    gd: lsp_goto_definition
    K: lsp_hover
commands:
  LspReferences: lua vim.lsp.buf.references_to_quickfix
plugins:
  telescope:
    url: github.com/telescope/telescope
    version: v2.1.1
```

```sh
nvim-yaml validate
nvim-yaml install
```
